excluded:
  - Pods
disabled_rules:
  - trailing_whitespace
identifier_name:
  excluded:
    - id
line_length:
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  ignores_function_declarations: true
